//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.4927
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kitos.Bolsa.Informes {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RUTAS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RUTAS() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kitos.Bolsa.Informes.RUTAS", typeof(RUTAS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/ABERTIS/isin/ES0111845014/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_ABE {
            get {
                return ResourceManager.GetString("AHORRO_ABE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/ABENGOA/isin/ES0105200416/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_ABG {
            get {
                return ResourceManager.GetString("AHORRO_ABG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/ACS/isin/ES0167050915/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_ACS {
            get {
                return ResourceManager.GetString("AHORRO_ACS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/ACERINOX/isin/ES0132105018/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_ACX {
            get {
                return ResourceManager.GetString("AHORRO_ACX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/AMADEUS/isin/ES0109067019/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_AMS {
            get {
                return ResourceManager.GetString("AHORRO_AMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/ACCIONA/isin/ES0125220311/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_ANA {
            get {
                return ResourceManager.GetString("AHORRO_ANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/BBVA/isin/ES0113211835/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_BBVA {
            get {
                return ResourceManager.GetString("AHORRO_BBVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/BANKINTER/isin/ES0113679I37/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_BKT {
            get {
                return ResourceManager.GetString("AHORRO_BKT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/BME/isin/ES0115056139/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_BME {
            get {
                return ResourceManager.GetString("AHORRO_BME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/CRITERIA/isin/ES0140609019/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_CRI {
            get {
                return ResourceManager.GetString("AHORRO_CRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/EBRO%20FOODS/isin/ES0112501012/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_EBRO {
            get {
                return ResourceManager.GetString("AHORRO_EBRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/ENDESA/isin/ES0130670112/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_ELE {
            get {
                return ResourceManager.GetString("AHORRO_ELE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/ENAGAS/isin/ES0130960018/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_ENG {
            get {
                return ResourceManager.GetString("AHORRO_ENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/FCC/isin/ES0122060314/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_FCC {
            get {
                return ResourceManager.GetString("AHORRO_FCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/FERROVIAL/isin/ES0118900010/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_FER {
            get {
                return ResourceManager.GetString("AHORRO_FER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/GAMESA/isin/ES0143416115/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_GAM {
            get {
                return ResourceManager.GetString("AHORRO_GAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/GAS%20NATURAL/isin/ES0116870314/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_GAS {
            get {
                return ResourceManager.GetString("AHORRO_GAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/GRIFOLS/isin/ES0171996012/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_GRF {
            get {
                return ResourceManager.GetString("AHORRO_GRF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/IBERDROLA/isin/ES0144580Y14/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_IBE {
            get {
                return ResourceManager.GetString("AHORRO_IBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/IBERDROLA%20RENOV/isin/ES0147645016/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_IBR {
            get {
                return ResourceManager.GetString("AHORRO_IBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/INDRA/isin/ES0118594417/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_IDR {
            get {
                return ResourceManager.GetString("AHORRO_IDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/INDITEX/isin/ES0148396015/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_ITX {
            get {
                return ResourceManager.GetString("AHORRO_ITX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/MAPFRE/isin/ES0124244E34/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_MAP {
            get {
                return ResourceManager.GetString("AHORRO_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/ARCELOR%20MITTAL/isin/LU0323134006/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_MTS {
            get {
                return ResourceManager.GetString("AHORRO_MTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/OHL/isin/ES0142090317/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_OHL {
            get {
                return ResourceManager.GetString("AHORRO_OHL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/B.%20%20POPULAR/isin/ES0113790531/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_POP {
            get {
                return ResourceManager.GetString("AHORRO_POP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/REE/isin/ES0173093115/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_REE {
            get {
                return ResourceManager.GetString("AHORRO_REE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/REPSOL%20YPF/isin/ES0173516115/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_REP {
            get {
                return ResourceManager.GetString("AHORRO_REP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/B.%20%20SABADELL/isin/ES0113860A34/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_SAB {
            get {
                return ResourceManager.GetString("AHORRO_SAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/SANTANDER/isin/ES0113900J37/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_SAN {
            get {
                return ResourceManager.GetString("AHORRO_SAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/SACYR/isin/ES0182870214/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_SYV {
            get {
                return ResourceManager.GetString("AHORRO_SYV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/TELEFONICA/isin/ES0178430E18/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_TEF {
            get {
                return ResourceManager.GetString("AHORRO_TEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/TELE%205/isin/ES0152503035/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_TL5 {
            get {
                return ResourceManager.GetString("AHORRO_TL5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.ahorro.com/acnet/fichas/ficha_valor.acnet/IBEX%20%2035/TECNICAS%20REUNIDAS/isin/ES0178165017/marketCode/09/submarketId/09.html.
        /// </summary>
        internal static string AHORRO_TRE {
            get {
                return ResourceManager.GetString("AHORRO_TRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/abertis/.
        /// </summary>
        internal static string CINCO_DIAS_ABE {
            get {
                return ResourceManager.GetString("CINCO_DIAS_ABE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/abengoa/.
        /// </summary>
        internal static string CINCO_DIAS_ABG {
            get {
                return ResourceManager.GetString("CINCO_DIAS_ABG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/acs/.
        /// </summary>
        internal static string CINCO_DIAS_ACS {
            get {
                return ResourceManager.GetString("CINCO_DIAS_ACS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/acerinox/.
        /// </summary>
        internal static string CINCO_DIAS_ACX {
            get {
                return ResourceManager.GetString("CINCO_DIAS_ACX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/amadeus/.
        /// </summary>
        internal static string CINCO_DIAS_AMS {
            get {
                return ResourceManager.GetString("CINCO_DIAS_AMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/acciona/.
        /// </summary>
        internal static string CINCO_DIAS_ANA {
            get {
                return ResourceManager.GetString("CINCO_DIAS_ANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/bbva/.
        /// </summary>
        internal static string CINCO_DIAS_BBVA {
            get {
                return ResourceManager.GetString("CINCO_DIAS_BBVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/bankinter/.
        /// </summary>
        internal static string CINCO_DIAS_BKT {
            get {
                return ResourceManager.GetString("CINCO_DIAS_BKT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/bme/.
        /// </summary>
        internal static string CINCO_DIAS_BME {
            get {
                return ResourceManager.GetString("CINCO_DIAS_BME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/criteria/.
        /// </summary>
        internal static string CINCO_DIAS_CRI {
            get {
                return ResourceManager.GetString("CINCO_DIAS_CRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/ebro-foods/.
        /// </summary>
        internal static string CINCO_DIAS_EBRO {
            get {
                return ResourceManager.GetString("CINCO_DIAS_EBRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/endesa/.
        /// </summary>
        internal static string CINCO_DIAS_ELE {
            get {
                return ResourceManager.GetString("CINCO_DIAS_ELE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/enagas/.
        /// </summary>
        internal static string CINCO_DIAS_ENG {
            get {
                return ResourceManager.GetString("CINCO_DIAS_ENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/fcc/.
        /// </summary>
        internal static string CINCO_DIAS_FCC {
            get {
                return ResourceManager.GetString("CINCO_DIAS_FCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/ferrovial/.
        /// </summary>
        internal static string CINCO_DIAS_FER {
            get {
                return ResourceManager.GetString("CINCO_DIAS_FER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/gamesa/.
        /// </summary>
        internal static string CINCO_DIAS_GAM {
            get {
                return ResourceManager.GetString("CINCO_DIAS_GAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/gas-natural/.
        /// </summary>
        internal static string CINCO_DIAS_GAS {
            get {
                return ResourceManager.GetString("CINCO_DIAS_GAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/grifols/.
        /// </summary>
        internal static string CINCO_DIAS_GRF {
            get {
                return ResourceManager.GetString("CINCO_DIAS_GRF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/iberdrola/.
        /// </summary>
        internal static string CINCO_DIAS_IBE {
            get {
                return ResourceManager.GetString("CINCO_DIAS_IBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/iberdrola-renovables/.
        /// </summary>
        internal static string CINCO_DIAS_IBR {
            get {
                return ResourceManager.GetString("CINCO_DIAS_IBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/indra/.
        /// </summary>
        internal static string CINCO_DIAS_IDR {
            get {
                return ResourceManager.GetString("CINCO_DIAS_IDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/inditex/.
        /// </summary>
        internal static string CINCO_DIAS_ITX {
            get {
                return ResourceManager.GetString("CINCO_DIAS_ITX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/mapfre/.
        /// </summary>
        internal static string CINCO_DIAS_MAP {
            get {
                return ResourceManager.GetString("CINCO_DIAS_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/arcelor/.
        /// </summary>
        internal static string CINCO_DIAS_MTS {
            get {
                return ResourceManager.GetString("CINCO_DIAS_MTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/ohl/.
        /// </summary>
        internal static string CINCO_DIAS_OHL {
            get {
                return ResourceManager.GetString("CINCO_DIAS_OHL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/banco-popular/.
        /// </summary>
        internal static string CINCO_DIAS_POP {
            get {
                return ResourceManager.GetString("CINCO_DIAS_POP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/ree/.
        /// </summary>
        internal static string CINCO_DIAS_REE {
            get {
                return ResourceManager.GetString("CINCO_DIAS_REE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/repsol-ypf/.
        /// </summary>
        internal static string CINCO_DIAS_REP {
            get {
                return ResourceManager.GetString("CINCO_DIAS_REP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/sabadell/.
        /// </summary>
        internal static string CINCO_DIAS_SAB {
            get {
                return ResourceManager.GetString("CINCO_DIAS_SAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/santander/.
        /// </summary>
        internal static string CINCO_DIAS_SAN {
            get {
                return ResourceManager.GetString("CINCO_DIAS_SAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/sacyr-vallehermoso/.
        /// </summary>
        internal static string CINCO_DIAS_SYV {
            get {
                return ResourceManager.GetString("CINCO_DIAS_SYV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/telefonica/.
        /// </summary>
        internal static string CINCO_DIAS_TEF {
            get {
                return ResourceManager.GetString("CINCO_DIAS_TEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/telecinco/.
        /// </summary>
        internal static string CINCO_DIAS_TL5 {
            get {
                return ResourceManager.GetString("CINCO_DIAS_TL5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://www.cincodias.com/empresa/tecnicas-reunidas/.
        /// </summary>
        internal static string CINCO_DIAS_TRE {
            get {
                return ResourceManager.GetString("CINCO_DIAS_TRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-ABE.
        /// </summary>
        internal static string SELFBANK_ABE {
            get {
                return ResourceManager.GetString("SELFBANK_ABE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-ABG.
        /// </summary>
        internal static string SELFBANK_ABG {
            get {
                return ResourceManager.GetString("SELFBANK_ABG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-ACS.
        /// </summary>
        internal static string SELFBANK_ACS {
            get {
                return ResourceManager.GetString("SELFBANK_ACS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-ACX.
        /// </summary>
        internal static string SELFBANK_ACX {
            get {
                return ResourceManager.GetString("SELFBANK_ACX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-AMS.
        /// </summary>
        internal static string SELFBANK_AMS {
            get {
                return ResourceManager.GetString("SELFBANK_AMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-ANA.
        /// </summary>
        internal static string SELFBANK_ANA {
            get {
                return ResourceManager.GetString("SELFBANK_ANA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-BBVA.
        /// </summary>
        internal static string SELFBANK_BBVA {
            get {
                return ResourceManager.GetString("SELFBANK_BBVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-BKT.
        /// </summary>
        internal static string SELFBANK_BKT {
            get {
                return ResourceManager.GetString("SELFBANK_BKT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-BME.
        /// </summary>
        internal static string SELFBANK_BME {
            get {
                return ResourceManager.GetString("SELFBANK_BME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-CRI.
        /// </summary>
        internal static string SELFBANK_CRI {
            get {
                return ResourceManager.GetString("SELFBANK_CRI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-EBRO.
        /// </summary>
        internal static string SELFBANK_EBRO {
            get {
                return ResourceManager.GetString("SELFBANK_EBRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-ELE.
        /// </summary>
        internal static string SELFBANK_ELE {
            get {
                return ResourceManager.GetString("SELFBANK_ELE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-ENG.
        /// </summary>
        internal static string SELFBANK_ENG {
            get {
                return ResourceManager.GetString("SELFBANK_ENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-FCC.
        /// </summary>
        internal static string SELFBANK_FCC {
            get {
                return ResourceManager.GetString("SELFBANK_FCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-FER.
        /// </summary>
        internal static string SELFBANK_FER {
            get {
                return ResourceManager.GetString("SELFBANK_FER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-GAM.
        /// </summary>
        internal static string SELFBANK_GAM {
            get {
                return ResourceManager.GetString("SELFBANK_GAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-GAS.
        /// </summary>
        internal static string SELFBANK_GAS {
            get {
                return ResourceManager.GetString("SELFBANK_GAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-GRF.
        /// </summary>
        internal static string SELFBANK_GRF {
            get {
                return ResourceManager.GetString("SELFBANK_GRF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-IBE.
        /// </summary>
        internal static string SELFBANK_IBE {
            get {
                return ResourceManager.GetString("SELFBANK_IBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-IBR.
        /// </summary>
        internal static string SELFBANK_IBR {
            get {
                return ResourceManager.GetString("SELFBANK_IBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-IDR.
        /// </summary>
        internal static string SELFBANK_IDR {
            get {
                return ResourceManager.GetString("SELFBANK_IDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-ITX.
        /// </summary>
        internal static string SELFBANK_ITX {
            get {
                return ResourceManager.GetString("SELFBANK_ITX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-MAP.
        /// </summary>
        internal static string SELFBANK_MAP {
            get {
                return ResourceManager.GetString("SELFBANK_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-MTS.
        /// </summary>
        internal static string SELFBANK_MTS {
            get {
                return ResourceManager.GetString("SELFBANK_MTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-OHL.
        /// </summary>
        internal static string SELFBANK_OHL {
            get {
                return ResourceManager.GetString("SELFBANK_OHL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-POP.
        /// </summary>
        internal static string SELFBANK_POP {
            get {
                return ResourceManager.GetString("SELFBANK_POP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-REE.
        /// </summary>
        internal static string SELFBANK_REE {
            get {
                return ResourceManager.GetString("SELFBANK_REE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-REP.
        /// </summary>
        internal static string SELFBANK_REP {
            get {
                return ResourceManager.GetString("SELFBANK_REP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-SAB.
        /// </summary>
        internal static string SELFBANK_SAB {
            get {
                return ResourceManager.GetString("SELFBANK_SAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-SAN.
        /// </summary>
        internal static string SELFBANK_SAN {
            get {
                return ResourceManager.GetString("SELFBANK_SAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-SYV.
        /// </summary>
        internal static string SELFBANK_SYV {
            get {
                return ResourceManager.GetString("SELFBANK_SYV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-TEF.
        /// </summary>
        internal static string SELFBANK_TEF {
            get {
                return ResourceManager.GetString("SELFBANK_TEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-TL5.
        /// </summary>
        internal static string SELFBANK_TL5 {
            get {
                return ResourceManager.GetString("SELFBANK_TL5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://api.selfbank.es/cotizaciones.phtml?symbol=FF55-TRE.
        /// </summary>
        internal static string SELFBANK_TRE {
            get {
                return ResourceManager.GetString("SELFBANK_TRE", resourceCulture);
            }
        }
    }
}
